logFilters:
  - code: YN0060
    level: warning
  - code: YN0002
    level: warning
  - code: YN0086
    level: warning

nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.13.0.cjs

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: '*'
  next@*:
    dependencies:
      '@vanilla-extract/next-plugin': '*'
