import { createThemeContract } from '@vanilla-extract/css';

export const vars = createThemeContract({
  color: {
    white: null,
    black: null,
    brand: {
      primary: null,
      primaryLight: null,
      primaryBg: null,
    },
    semantic: {
      success: null,
      successBg: null,
      danger: null,
      dangerBg: null,
      warning: null,
      warningBg: null,
      info: null,
      infoBg: null,
    },
    neutral: {
      n900: null,
      n700: null,
      n500: null,
      n400: null,
      n300: null,
      n200: null,
      n100: null,
      nSurface: null,
    },
  },
  typography: {
    fontFamily: null,
    fontSize: {
      xxs: null,
      xs: null,
      sm: null,
      base: null,
      md: null,
      lg: null,
      xl: null,
      '2xl': null,
      '3xl': null,
      '4xl': null,
    },
    fontWeight: {
      regular: null,
      medium: null,
      semiBold: null,
      bold: null,
      extraBold: null,
    },
    lineHeight: {
      sm: null,
      md: null,
      lg: null,
      xl: null,
      '2xl': null,
      '3xl': null,
    },
    letterSpacing: {
      sm: null,
      md: null,
      lg: null,
    },
  },
  space: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
  },
  radius: {
    sm: null,
    md: null,
    lg: null,
    xl: null,
  },
});
